from pydantic import BaseModel


class TransactionRequest(BaseModel):
    TX_AMOUNT: float

    TX_HOUR: int
    TX_DAY_OF_WEEK: int

    CUSTOMER_TIME_SINCE_PREV: float
    CUSTOMER_PREV_AMOUNT: float
    CUSTOMER_TX_COUNT_BEFORE: int
    CUSTOMER_TX_COUNT_5M: int
    CUSTOMER_TX_COUNT_1H: int
    CUSTOMER_TX_COUNT_24H: int
    CUSTOMER_AVG_AMOUNT_BEFORE: float
    CUSTOMER_AMOUNT_DEVIATION: float
    CUSTOMER_AMOUNT_RATIO: float
    CUSTOMER_HAS_HISTORY: int

    TERMINAL_TIME_SINCE_PREV: float
    TERMINAL_PREV_AMOUNT: float
    TERMINAL_TX_COUNT_BEFORE: int
    TERMINAL_TX_COUNT_5M: int
    TERMINAL_TX_COUNT_1H: int
    TERMINAL_TX_COUNT_24H: int
    TERMINAL_AVG_AMOUNT_BEFORE: float
    TERMINAL_AMOUNT_DEVIATION: float
    TERMINAL_AMOUNT_RATIO: float
    TERMINAL_HAS_HISTORY: int

    SYSTEM_TX_COUNT_5M: int
    SYSTEM_TX_COUNT_1H: int
    SYSTEM_TX_COUNT_24H: int